<a href="https://colab.research.google.com/github/rkmaccha/FlaskWebApp_ML_Basic/blob/main/DummyProject_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ML_Projects/datasets/homeprices_multi_00.csv")

In [ ]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  520000
1  3000       3.0   15  565000
2  3200       4.0   16  595000
3  3600       3.0   30  595000
4  4000       NaN    8  760000

In [ ]:
df.shape

(12, 4)

In [ ]:
df

area  bedrooms  age   price
0   2600       3.0   20  520000
1   3000       3.0   15  565000
2   3200       4.0   16  595000
3   3600       3.0   30  595000
4   4000       NaN    8  760000
5   4150       6.0   10  790000
6   3000       3.0   15  550000
7   3500       4.0   12  600000
8   3100       4.0   18  610000
9   3800       3.0   30  595000
10  4000       5.0    8  760000
11  4500       6.0    8  850000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      12 non-null     int64  
 1   bedrooms  11 non-null     float64
 2   age       12 non-null     int64  
 3   price     12 non-null     int64  
dtypes: float64(1), int64(3)
memory usage: 512.0 bytes


In [ ]:
df.isnull()

area  bedrooms    age  price
0   False     False  False  False
1   False     False  False  False
2   False     False  False  False
3   False     False  False  False
4   False      True  False  False
5   False     False  False  False
6   False     False  False  False
7   False     False  False  False
8   False     False  False  False
9   False     False  False  False
10  False     False  False  False
11  False     False  False  False

In [ ]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [ ]:
median_br = df['bedrooms'].median()

In [ ]:
median_br

4.0

In [ ]:
df['bedrooms'] = df['bedrooms'].fillna(median_br)

In [ ]:
df

area  bedrooms  age   price
0   2600       3.0   20  520000
1   3000       3.0   15  565000
2   3200       4.0   16  595000
3   3600       3.0   30  595000
4   4000       4.0    8  760000
5   4150       6.0   10  790000
6   3000       3.0   15  550000
7   3500       4.0   12  600000
8   3100       4.0   18  610000
9   3800       3.0   30  595000
10  4000       5.0    8  760000
11  4500       6.0    8  850000

In [ ]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [ ]:
X= df.drop(columns=['price'],axis=1)
y = df['price']

In [ ]:
reg_model = LinearRegression()

In [ ]:
reg_model.fit(X,y)

LinearRegression()

In [ ]:
reg_model.predict([[3200,4,18]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([602279.17645019])

In [ ]:
reg_model.predict([[4000,5,8]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([755812.11080189])

In [ ]:
reg_model.score(X,y)

0.9558416604941481

In [ ]:
import pickle

with open("/content/drive/MyDrive/ML_Projects/datasets/pickles/lr_multimodel.pkl","wb") as f:
  pickle.dump(reg_model,f)

In [ ]:
with open("/content/drive/MyDrive/ML_Projects/datasets/pickles/lr_multimodel.pkl","rb") as f:
  model = pickle.load(f)

In [ ]:
model.predict([[4000,5,8]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([755812.11080189])